### ISSUE TITLE
click node to inspect it.

### ISSUE THREAD

**Issue by paulirish** [kdzwinel/DOMListenerExtension#3]
this is admittedly harder to do than it should be.. but...

it would be amazing.

**Comment by kdzwinel** [comment]
Try shift + click :) Enjoy!

**Comment by paulirish** [comment]
AMAZING.

**Comment by paulirish** [comment]
why not just click?

**Comment by paulirish** [comment]
FWIW https://github.com/PolymerLabs/polymer-devtools-extension/blob/master/panel-orig.js has a crazy roundable method for faking a highlight on the element during hover.

**Comment by paulirish** [comment]
Ah you are such a pro. 
https://github.com/kdzwinel/DOMListenerExtension/blob/1db80296ed83c5878ca0cedbcc347ff5df865621/js/ContentScriptProxy.js#L17-L22

very nice

**Comment by paulirish** [comment]
proposal: highlight node on hover, inspect node on click

**Comment by kdzwinel** [comment]
Click highlights nodes (when possible), shift+click inspects them. But maybe, you are right. Highlight should work on hover (same as in DT). I'll open a ticket for that.

Thanks for a tip with panel-orig.js! I definitely need a better way of highlighting (currently it's just Node.animate + box-shadow). The issue here is that my highlight method must not cause any mutations.
